"""add_policy_agent_tool_tables

Revision ID: f174bb2bb84c
Revises: e7a1b3c5d9f2
Create Date: 2026-07-06 22:20:13.414575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f174bb2bb84c'
down_revision: Union[str, Sequence[str], None] = 'e7a1b3c5d9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('statements', sa.JSON(), nullable=False),
    sa.Column('grn', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.Enum('ORGANIZATION', 'USER', 'AGENT', 'TOOL', 'POLICY', 'MEMORY', 'MODEL', 'SOLUTION', 'WORKFLOW', 'CONNECTOR', 'DOCUMENT', 'FILE', name='resourcetype', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'DEPRECATED', 'DELETED', name='resourcestate', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('grn')
    )
    op.create_index(op.f('ix_policies_org_id'), 'policies', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_org_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
